### ISSUE TITLE
carddav2phone.sh fails with SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by schaechtelchen** [alexanderharm/node-carddav2phone#10]
I get warnings and syntax errors when running ./carddav2phone.sh

```
root@v7:~/weg/node-carddav2phone# ./carddav2phone.sh
Bereits aktuell.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sindresorhus/is@5.3.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@szmarczak/http-timer@5.0.1',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'awesome-phonenumber@5.3.1',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'cacheable-lookup@7.0.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'cacheable-request@10.2.9',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'form-data-encoder@2.1.4',
npm WARN EBADENGINE   required: { node: '>= 14.17' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'formdata-node@5.0.0',
npm WARN EBADENGINE   required: { node: '>= 14.17' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fs-extra@11.1.1',
npm WARN EBADENGINE   required: { node: '>=14.14' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'got@12.6.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'normalize-url@8.0.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'responselike@3.0.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'web-streams-polyfill@4.0.0-beta.3',
npm WARN EBADENGINE   required: { node: '>= 14' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }

added 87 packages in 1s

12 packages are looking for funding
  run `npm fund` for details
file:///root/weg/node-carddav2phone/node_modules/got/dist/source/create.js:48
            const handler = defaults.handlers[iteration++] ?? lastHandler;
                                                            ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
```

Likely with dist/index.js

```
root@v7:~/weg/node-carddav2phone# node dist/index.js
file:///root/weg/node-carddav2phone/node_modules/got/dist/source/core/options.js:291
    const initHooks = options.hooks?.init;
                                    ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
root@v7:~/weg/node-carddav2phone# node dist/index.js
file:///root/weg/node-carddav2phone/node_modules/got/dist/source/create.js:48
            const handler = defaults.handlers[iteration++] ?? lastHandler;
                                                            ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)


```

OS: debian 11 bullseye with distributions own node/npm etc.

**Comment by alexanderharm** [comment]
As the error message says, you need to use at least a node version of 14.16 or above. You are using node v12.

**Comment by schaechtelchen** [comment]
Danke. Mit einer aktuelleren nodejs läuft's.
(Ich hatte erwartet, dass das aktuelle debian unterstützt wird, aber dessen nodejs ist ja tatsächlich schon gut abgehangen.)

Das yealink xml wurde aus 1300 Adressen generiert, jetzt brauche ich nur noch ein Telefon :)

--
Thank you. It works with a more recent nodejs.
(I had expected the current debian to be supported, but its nodejs is actually well worn out).

The yealink xml was generated from 1300 addresses, now I just need a phone :)

**Comment by alexanderharm** [comment]
Hi, das aktuelle Debian wäre Bookworm und das wäre ausreichend:

```
root@lb:~# apt-cache policy nodejs
nodejs:
  Installed: (none)
  Candidate: 18.13.0+dfsg1-1
  Version table:
     18.13.0+dfsg1-1 500
        500 http://ftp.debian.org/debian bookworm/main amd64 Packages
```

**Comment by schaechtelchen** [comment]
> Hi, das aktuelle Debian wäre Bookworm und das wäre ausreichend:

Stimmt, hatte ich verdrängt :)
Das heißt, wieder nervige updates machen.
