### ISSUE TITLE
Client files are not being created

### ISSUE THREAD

**Issue by gitcat555** [alexanderharm/node-carddav2phone#5]
Hi there,
your script seems to be exactly what I'm looking for but I can't seem to get it to work. I created my own settings.json, entered all the credentials etc., the webroot and dir (the folder does exist) but for some reason, the structure and files are not being created. I get a TypeError on first run but when I run it again it seems to work normally and a .json file that holds all the contacts from my CardDAV server (Nextcloud) is being created correctly, just not the xcap files for the webserver. What am I doing wrong?

Output of first run:
`CardDAV: creating clients

nextcloud_xxxxxxxxxxxxxxxxxxxxxxxxxx: updates available
CardDAV: updates available
Fritz!Box: start
LDAP: start
Fritz!Box: attempting login
Fritz!Box: authenticate
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at __values (/root/gitstuff/node-carddav2phone/dist/ldap.js:14:72)
    at ldapProcessCards (/root/gitstuff/node-carddav2phone/dist/ldap.js:83:46)
    at _loop_1 (/root/gitstuff/node-carddav2phone/dist/ldap.js:40:24)
    at ldapHandler (/root/gitstuff/node-carddav2phone/dist/ldap.js:45:9)
    at phoneHandlers (/root/gitstuff/node-carddav2phone/dist/index.js:21:46)
    at /root/gitstuff/node-carddav2phone/dist/index.js:37:16
    at invokeCallback (/root/gitstuff/node-carddav2phone/node_modules/es6-promise/dist/es6-promise.js:408:15)
    at publish (/root/gitstuff/node-carddav2phone/node_modules/es6-promise/dist/es6-promise.js:391:7)
    at flush (/root/gitstuff/node-carddav2phone/node_modules/es6-promise/dist/es6-promise.js:128:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Fritz!Box: login successful
Fritz!Box: trying to update
Fritz!Box: update successful`

Output of second run:
`Already checked for updates today.

CardDAV: creating clients
nextcloud_xxxxxxxxxxxxxxxxxxxxxxxxxxx: no updates
CardDAV: no updates available`

Webroot is "/var/www/html/" and dir is "phone" but in /var/www/html/phone there are absolutely NO files.

**Comment by gitcat555** [comment]
After fiddling with it for a while, I got it to work :)

**Comment by theniwo** [comment]
So and what was your fix?

It would be helpful for others to see what you have done to fix it.
