### ISSUE TITLE
TypeError: awesome_phonenumber_1.default is not a constructor

### ISSUE THREAD

**Issue by unclesam87** [alexanderharm/node-carddav2phone#6]
Hey,
i installed that scrip on a fresh debian 11 with npm and nginx installed, git cloned ur repo and run npm i.
i configured ur settings.json so that only one webdav account is in it and snom xcap.
when i do the first run i get the following error:
`TypeError: awesome_phonenumber_1.default is not a constructor
TypeError: awesome_phonenumber_1.default is not a constructor
    at utilNumberConvert (/root/node-carddav2phone/dist/utils.js:95:23)
    at utilParseVcard (/root/node-carddav2phone/dist/utils.js:217:26)
    at snomXcapProcessCards (/root/node-carddav2phone/dist/snom.js:118:58)
    at _loop_1 (/root/node-carddav2phone/dist/snom.js:71:24)
    at snomXcapHandler (/root/node-carddav2phone/dist/snom.js:76:9)
    at snomHandler (/root/node-carddav2phone/dist/snom.js:54:27)
    at phoneHandlers (/root/node-carddav2phone/dist/index.js:25:46)
    at /root/node-carddav2phone/dist/index.js:37:16
    at invokeCallback (/root/node-carddav2phone/node_modules/es6-promise/dist/es6-promise.js:408:15)
    at publish (/root/node-carddav2phone/node_modules/es6-promise/dist/es6-promise.js:391:7)`

**Comment by alexanderharm** [comment]
Sorry, missed the API change in the library. Is fixed now.
